# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/tareasSpringBoot
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
server.port=8080
# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#Al no tener el script de la BD, creado ni un CSV de carga pongo en 
#comentarios un usuario Admin con la pass 1234, para probar el login.

spring.security.user.name=Admin
spring.security.user.password=1234
spring.security.user.roles=ADMIN